name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality:
    runs-on: ubuntu-latest

    name: Code Quality

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, ctype, json, bcmath
          tools: composer:v2


      - name: Configure composer auth
        run: composer config -g github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: Run Pint
        run: vendor/bin/pint --test

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress

      - name: Run Rector (dry-run)
        run: vendor/bin/rector process --dry-run

  test:
    runs-on: ubuntu-latest

    name: Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, ctype, json, bcmath
          tools: composer:v2, pint, phpstan, rector, pest


      - name: Configure composer auth
        run: composer config -g github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: Run Tests
        run: vendor/bin/pest --coverage

      - name: Check coverage
        run: vendor/bin/pest --min=80